version: "3"
networks:
  postgres_network:
    driver: overlay
  rabbit_network:
    driver: overlay
  redis_network:
    driver: overlay
  services_network:
    driver: overlay

volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
  pg_2_data:
    driver: local
    
services:
  finance_api:
    image: sergeyer/trrp_finance_api:latest
    networks:
     - services_network
    environment:
     - USER_SERVICE=user_service
     
  price_updater:
    image: sergeyer/trrp_price_updater:latest
    networks:
     - services_network
     - redis_network
    environment:
     - UPDATE_FREQUENCY=60
     - FINANCE_API=finance_api
  
  stats_calculator:
    image: sergeyer/trrp_stats_calculator:latest
    networks:
     - services_network
     - redis_network
     - rabbit_network
    environment:
     - STAT_EXPIRATION_TIME=60
     - USER_SERVICE=user_service
     - FINANCE_API=finance_api
     - RABBIT_MQ_HOST=rabbit
     
  auth:
    build: .
    image: sergeyer/trrp_auth:latest
    networks:
    - postgres_network # подключайте только те сервисы, что нужно
    - services_network
    environment:
     - POSTGRES_CONNECTION=postgres
    depends_on:
     - user_service
  
  user_service:
    build: .
    image: sergeyer/trrp_user_service:latest
    networks:
    - postgres_network # подключайте только те сервисы, что нужно
    - services_network
    environment:
     - POSTGRES_CONNECTION=postgres
    depends_on:
     - postgres
  
  pg-0:
    image: bitnami/postgresql-repmgr:11
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
      - REPMGR_PASSWORD=postgres
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    networks:
      - postgres_network
  pg-1:
    image: bitnami/postgresql-repmgr:11
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
      - REPMGR_PASSWORD=postgres
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    networks:
      - postgres_network
  pg-2:
    image: bitnami/postgresql-repmgr:11
    volumes:
      - pg_2_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
      - REPMGR_PASSWORD=postgres
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
    networks:
      - postgres_network
      
  postgres:
    image: bitnami/pgpool:4
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0,1:pg-1,2:pg-2
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=postgres
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=postgres
      - PGPOOL_ADMIN_USERNAME=postgres
      - PGPOOL_ADMIN_PASSWORD=postgres
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
     - pg-0
     - pg-1
     - pg-2
  rabbit:
        image: rabbitmq:3-management-alpine
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: rabbit
        networks:
         - rabbit_network
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=redis
    networks:
      - redis_network
    ports:
     - 6379:6379
  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=redis
      - REDIS_PASSWORD=redis
    depends_on:
      - redis
    deploy:
      replicas: 3
    networks:
      - redis_network
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_PASSWORD=redis
    depends_on:
      - redis
      - redis-slave
    networks:
      - redis_network
    deploy:
      replicas: 3
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=redis
    networks:
      - redis_network
    ports:
     - 6379:6379
  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=redis
      - REDIS_PASSWORD=redis
    depends_on:
      - redis
    deploy:
      replicas: 3
    networks:
      - redis_network
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_PASSWORD=redis
    depends_on:
      - redis
      - redis-slave
    networks:
      - redis_network
    deploy:
      replicas: 3
  
  
  
     
