apiVersion: v1
kind: Namespace
metadata:
  name: kubegres
---
apiVersion: v1
kind: Secret
metadata:
  name: mypostgres-secret
  namespace: kubegres
type: Opaque
stringData:
  superUserPassword: postgres
  replicationUserPassword: postgres