version: "3"
networks:
  rabbit_network:
    driver: overlay
    
services:
    rabbit:
        image: rabbitmq:3-management-alpine
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: rabbit
        #ports:
            #- 5672:5672
            #- 15672:15672
        networks:
         - rabbit_network