# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auth.proto',
  package='authService',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nauth.proto\x12\x0b\x61uthService\"7\n\x15user_password_request\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"$\n\x13\x63heck_token_request\x12\r\n\x05token\x18\x01 \x01(\t\"\x1c\n\tok_answer\x12\x0f\n\x07ok_code\x18\x01 \x01(\x05\"\x1d\n\x0ctoken_answer\x12\r\n\x05token\x18\x01 \x01(\t2\xee\x01\n\x04\x61uth\x12K\n\x08GetToken\x12\".authService.user_password_request\x1a\x19.authService.token_answer\"\x00\x12H\n\nCheckToken\x12 .authService.check_token_request\x1a\x16.authService.ok_answer\"\x00\x12O\n\x0cRegisterUser\x12\".authService.user_password_request\x1a\x19.authService.token_answer\"\x00\x62\x06proto3'
)




_USER_PASSWORD_REQUEST = _descriptor.Descriptor(
  name='user_password_request',
  full_name='authService.user_password_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='authService.user_password_request.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='authService.user_password_request.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=82,
)


_CHECK_TOKEN_REQUEST = _descriptor.Descriptor(
  name='check_token_request',
  full_name='authService.check_token_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='authService.check_token_request.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=120,
)


_OK_ANSWER = _descriptor.Descriptor(
  name='ok_answer',
  full_name='authService.ok_answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok_code', full_name='authService.ok_answer.ok_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=150,
)


_TOKEN_ANSWER = _descriptor.Descriptor(
  name='token_answer',
  full_name='authService.token_answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='authService.token_answer.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['user_password_request'] = _USER_PASSWORD_REQUEST
DESCRIPTOR.message_types_by_name['check_token_request'] = _CHECK_TOKEN_REQUEST
DESCRIPTOR.message_types_by_name['ok_answer'] = _OK_ANSWER
DESCRIPTOR.message_types_by_name['token_answer'] = _TOKEN_ANSWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

user_password_request = _reflection.GeneratedProtocolMessageType('user_password_request', (_message.Message,), {
  'DESCRIPTOR' : _USER_PASSWORD_REQUEST,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:authService.user_password_request)
  })
_sym_db.RegisterMessage(user_password_request)

check_token_request = _reflection.GeneratedProtocolMessageType('check_token_request', (_message.Message,), {
  'DESCRIPTOR' : _CHECK_TOKEN_REQUEST,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:authService.check_token_request)
  })
_sym_db.RegisterMessage(check_token_request)

ok_answer = _reflection.GeneratedProtocolMessageType('ok_answer', (_message.Message,), {
  'DESCRIPTOR' : _OK_ANSWER,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:authService.ok_answer)
  })
_sym_db.RegisterMessage(ok_answer)

token_answer = _reflection.GeneratedProtocolMessageType('token_answer', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN_ANSWER,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:authService.token_answer)
  })
_sym_db.RegisterMessage(token_answer)



_AUTH = _descriptor.ServiceDescriptor(
  name='auth',
  full_name='authService.auth',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=184,
  serialized_end=422,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetToken',
    full_name='authService.auth.GetToken',
    index=0,
    containing_service=None,
    input_type=_USER_PASSWORD_REQUEST,
    output_type=_TOKEN_ANSWER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckToken',
    full_name='authService.auth.CheckToken',
    index=1,
    containing_service=None,
    input_type=_CHECK_TOKEN_REQUEST,
    output_type=_OK_ANSWER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterUser',
    full_name='authService.auth.RegisterUser',
    index=2,
    containing_service=None,
    input_type=_USER_PASSWORD_REQUEST,
    output_type=_TOKEN_ANSWER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTH)

DESCRIPTOR.services_by_name['auth'] = _AUTH

# @@protoc_insertion_point(module_scope)
