apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: db-services
  labels:
    app: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service-container
        image: sergeyer/trrp_auth
        ports:
        - containerPort: 50051
        env:
        - name: POSTGRES_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: pg-config
              key: postgresConn
              
---
apiVersion: v1
kind: Service
metadata:
  namespace: db-services
  name: auth-service-grpc
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
 