version: "3"
services:
  auth:
    build: .
    image: sergeyer/stock_auth
    networks:
    - postgres_network # подключайте только те сервисы, что нужно
    - services_network
    environment:
     - POSTGRES_CONNECTION='postgres'
    depends_on:
     - user_service
     

     