# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("auth.proto", :syntax => :proto3) do
    add_message "authService.UserPasswordRequest" do
      optional :user, :string, 1
      optional :password, :string, 2
    end
    add_message "authService.CheckTokenRequest" do
      optional :token, :string, 1
    end
    add_message "authService.UserAnswer" do
      optional :user, :string, 1
    end
    add_message "authService.TokenAnswer" do
      optional :token, :string, 1
    end
  end
end

module AuthService
  UserPasswordRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authService.UserPasswordRequest").msgclass
  CheckTokenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authService.CheckTokenRequest").msgclass
  UserAnswer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authService.UserAnswer").msgclass
  TokenAnswer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authService.TokenAnswer").msgclass
end
