# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: auth.proto for package 'authService'

require 'grpc'
require 'rpc/auth_pb'

module AuthService
  module Auth
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'authService.auth'

      rpc :GetToken, ::AuthService::UserPasswordRequest, ::AuthService::TokenAnswer
      rpc :CheckToken, ::AuthService::CheckTokenRequest, ::AuthService::OkAnswer
      rpc :RegisterUser, ::AuthService::UserPasswordRequest, ::AuthService::TokenAnswer
    end

    Stub = Service.rpc_stub_class
  end
end
