# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_service.proto", :syntax => :proto3) do
    add_message "userService.StockToUserRequest" do
      optional :user, :string, 1
      optional :stock_code, :string, 2
    end
    add_message "userService.GetUserStocksRequest" do
      optional :user, :string, 1
    end
    add_message "userService.GetAllStocksRequest" do
    end
    add_message "userService.OkAnswer" do
      optional :ok_code, :int32, 1
    end
    add_message "userService.StockAnswer" do
      repeated :codes, :string, 1
    end
  end
end

module UserService
  StockToUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("userService.StockToUserRequest").msgclass
  GetUserStocksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("userService.GetUserStocksRequest").msgclass
  GetAllStocksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("userService.GetAllStocksRequest").msgclass
  OkAnswer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("userService.OkAnswer").msgclass
  StockAnswer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("userService.StockAnswer").msgclass
end
