# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user_service.proto for package 'userService'

require 'grpc'
require 'rpc/user_service_pb'

module UserService
  module UserService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'userService.user_service'

      rpc :AddStockToUser, ::UserService::StockToUserRequest, ::UserService::OkAnswer
      rpc :RemoveStockFromUser, ::UserService::StockToUserRequest, ::UserService::OkAnswer
      rpc :GetStocks, ::UserService::GetUserStocksRequest, ::UserService::StockAnswer
      rpc :GetAllStocks, ::UserService::GetAllStocksRequest, ::UserService::StockAnswer
    end

    Stub = Service.rpc_stub_class
  end
end
