# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Finance_API import Finance_API_pb2 as Finance__API__pb2


class StocksLoaderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_stocks = channel.unary_stream(
                '/StocksLoader/get_stocks',
                request_serializer=Finance__API__pb2.Get_stocks_request.SerializeToString,
                response_deserializer=Finance__API__pb2.Stock.FromString,
                )
        self.get_stocks_history = channel.unary_stream(
                '/StocksLoader/get_stocks_history',
                request_serializer=Finance__API__pb2.Stock_Codes.SerializeToString,
                response_deserializer=Finance__API__pb2.Stock.FromString,
                )


class StocksLoaderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_stocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_stocks_history(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StocksLoaderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_stocks': grpc.unary_stream_rpc_method_handler(
                    servicer.get_stocks,
                    request_deserializer=Finance__API__pb2.Get_stocks_request.FromString,
                    response_serializer=Finance__API__pb2.Stock.SerializeToString,
            ),
            'get_stocks_history': grpc.unary_stream_rpc_method_handler(
                    servicer.get_stocks_history,
                    request_deserializer=Finance__API__pb2.Stock_Codes.FromString,
                    response_serializer=Finance__API__pb2.Stock.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StocksLoader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StocksLoader(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_stocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/StocksLoader/get_stocks',
            Finance__API__pb2.Get_stocks_request.SerializeToString,
            Finance__API__pb2.Stock.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_stocks_history(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/StocksLoader/get_stocks_history',
            Finance__API__pb2.Stock_Codes.SerializeToString,
            Finance__API__pb2.Stock.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
