# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user_service.proto',
  package='userService',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12user_service.proto\x12\x0buserService\"6\n\x12StockToUserRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x12\n\nstock_code\x18\x02 \x01(\t\"$\n\x14GetUserStocksRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\"\x15\n\x13GetAllStocksRequest\"\x1b\n\x08OkAnswer\x12\x0f\n\x07ok_code\x18\x01 \x01(\x05\"\x1c\n\x0bStockAnswer\x12\r\n\x05\x63odes\x18\x01 \x03(\t2\xc5\x02\n\x0cuser_service\x12J\n\x0e\x41\x64\x64StockToUser\x12\x1f.userService.StockToUserRequest\x1a\x15.userService.OkAnswer\"\x00\x12O\n\x13RemoveStockFromUser\x12\x1f.userService.StockToUserRequest\x1a\x15.userService.OkAnswer\"\x00\x12J\n\tGetStocks\x12!.userService.GetUserStocksRequest\x1a\x18.userService.StockAnswer\"\x00\x12L\n\x0cGetAllStocks\x12 .userService.GetAllStocksRequest\x1a\x18.userService.StockAnswer\"\x00\x62\x06proto3'
)




_STOCKTOUSERREQUEST = _descriptor.Descriptor(
  name='StockToUserRequest',
  full_name='userService.StockToUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='userService.StockToUserRequest.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='userService.StockToUserRequest.stock_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=89,
)


_GETUSERSTOCKSREQUEST = _descriptor.Descriptor(
  name='GetUserStocksRequest',
  full_name='userService.GetUserStocksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='userService.GetUserStocksRequest.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=127,
)


_GETALLSTOCKSREQUEST = _descriptor.Descriptor(
  name='GetAllStocksRequest',
  full_name='userService.GetAllStocksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=150,
)


_OKANSWER = _descriptor.Descriptor(
  name='OkAnswer',
  full_name='userService.OkAnswer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok_code', full_name='userService.OkAnswer.ok_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=179,
)


_STOCKANSWER = _descriptor.Descriptor(
  name='StockAnswer',
  full_name='userService.StockAnswer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='codes', full_name='userService.StockAnswer.codes', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=209,
)

DESCRIPTOR.message_types_by_name['StockToUserRequest'] = _STOCKTOUSERREQUEST
DESCRIPTOR.message_types_by_name['GetUserStocksRequest'] = _GETUSERSTOCKSREQUEST
DESCRIPTOR.message_types_by_name['GetAllStocksRequest'] = _GETALLSTOCKSREQUEST
DESCRIPTOR.message_types_by_name['OkAnswer'] = _OKANSWER
DESCRIPTOR.message_types_by_name['StockAnswer'] = _STOCKANSWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StockToUserRequest = _reflection.GeneratedProtocolMessageType('StockToUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOCKTOUSERREQUEST,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:userService.StockToUserRequest)
  })
_sym_db.RegisterMessage(StockToUserRequest)

GetUserStocksRequest = _reflection.GeneratedProtocolMessageType('GetUserStocksRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERSTOCKSREQUEST,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:userService.GetUserStocksRequest)
  })
_sym_db.RegisterMessage(GetUserStocksRequest)

GetAllStocksRequest = _reflection.GeneratedProtocolMessageType('GetAllStocksRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLSTOCKSREQUEST,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:userService.GetAllStocksRequest)
  })
_sym_db.RegisterMessage(GetAllStocksRequest)

OkAnswer = _reflection.GeneratedProtocolMessageType('OkAnswer', (_message.Message,), {
  'DESCRIPTOR' : _OKANSWER,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:userService.OkAnswer)
  })
_sym_db.RegisterMessage(OkAnswer)

StockAnswer = _reflection.GeneratedProtocolMessageType('StockAnswer', (_message.Message,), {
  'DESCRIPTOR' : _STOCKANSWER,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:userService.StockAnswer)
  })
_sym_db.RegisterMessage(StockAnswer)



_USER_SERVICE = _descriptor.ServiceDescriptor(
  name='user_service',
  full_name='userService.user_service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=212,
  serialized_end=537,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddStockToUser',
    full_name='userService.user_service.AddStockToUser',
    index=0,
    containing_service=None,
    input_type=_STOCKTOUSERREQUEST,
    output_type=_OKANSWER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveStockFromUser',
    full_name='userService.user_service.RemoveStockFromUser',
    index=1,
    containing_service=None,
    input_type=_STOCKTOUSERREQUEST,
    output_type=_OKANSWER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetStocks',
    full_name='userService.user_service.GetStocks',
    index=2,
    containing_service=None,
    input_type=_GETUSERSTOCKSREQUEST,
    output_type=_STOCKANSWER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllStocks',
    full_name='userService.user_service.GetAllStocks',
    index=3,
    containing_service=None,
    input_type=_GETALLSTOCKSREQUEST,
    output_type=_STOCKANSWER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER_SERVICE)

DESCRIPTOR.services_by_name['user_service'] = _USER_SERVICE

# @@protoc_insertion_point(module_scope)
