version: '3'
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=redis
    networks:
      - redis_network
    ports:
     - 6379:6379
  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=redis
      - REDIS_PASSWORD=redis
    depends_on:
      - redis
    deploy:
      replicas: 3
    networks:
      - redis_network
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_PASSWORD=redis
    depends_on:
      - redis
      - redis-slave
    networks:
      - redis_network
    deploy:
      replicas: 3