apiVersion: v1
kind: Namespace
metadata:
  name: user-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-service-config
  namespace: user-service
data:
  postgresConn: mypostgres.kubegres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: user-service
  labels:
    app: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service-container
        image: sergeyer/trrp_user_service
        ports:
        - containerPort: 50051
        env:
        - name: POSTGRES_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: users-service-config
              key: postgresConn
              
---
apiVersion: v1
kind: Service
metadata:
  namespace: user-service
  name: user-service-grpc
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
 